// Generated from http://en.wikipedia.org/wiki/Graphic_display_resolutions
window.PubSub.publish('list.load', {'UPDATEDAT': 1334702012936, 'items': [
  {'name': 'QQVGA', 'size': {'min': '120', 'max': '160'}, 'details': '', 'favourite': '0'},
  {'name': 'HQVGA', 'size': {'min': '160', 'max': '240'}, 'details': '', 'favourite': '0'},
  {'name': 'QVGA', 'size': {'min': '240', 'max': '320'}, 'details': '', 'favourite': '0'},
  {'name': 'WQVGA', 'size': {'min': '240', 'max': '400'}, 'details': '', 'favourite': '0'},
  {'name': 'HVGA', 'size': {'min': '320', 'max': '480'}, 'details': '', 'favourite': '1'},
  {'name': 'VGA', 'size': {'min': '480', 'max': '640'}, 'details': '', 'favourite': '0'},
  {'name': 'WVGA', 'size': {'min': '480', 'max': '800'}, 'details': '', 'favourite': '0'},
  {'name': 'SVGA', 'size': {'min': '600', 'max': '800'}, 'details': '', 'favourite': '0'},
  {'name': 'DVGA', 'size': {'min': '640', 'max': '960'}, 'details': '', 'favourite': '0'},
  {'name': 'WSVGA', 'size': {'min': '576', 'max': '1024'}, 'details': '', 'favourite': '0'},
  {'name': 'WSVGA', 'size': {'min': '600', 'max': '1024'}, 'details': '', 'favourite': '0'},
  {'name': 'XGA', 'size': {'min': '768', 'max': '1024'}, 'details': '', 'favourite': '1'},
  {'name': 'WXGA', 'size': {'min': '720', 'max': '1280'}, 'details': '', 'favourite': '0'},
  {'name': 'WXGA', 'size': {'min': '768', 'max': '1280'}, 'details': '', 'favourite': '0'},
  {'name': 'WXGA', 'size': {'min': '800', 'max': '1280'}, 'details': '', 'favourite': '0'},
  {'name': 'WXGA', 'size': {'min': '768', 'max': '1360'}, 'details': '', 'favourite': '0'},
  {'name': 'WXGA', 'size': {'min': '768', 'max': '1366'}, 'details': '', 'favourite': '1'},
  {'name': 'XGA+', 'size': {'min': '864', 'max': '1152'}, 'details': '', 'favourite': '0'},
  {'name': 'WXGA+', 'size': {'min': '900', 'max': '1440'}, 'details': '', 'favourite': '0'},
  {'name': 'SXGA', 'size': {'min': '1024', 'max': '1280'}, 'details': '', 'favourite': '1'},
  {'name': 'SXGA+', 'size': {'min': '1050', 'max': '1400'}, 'details': '', 'favourite': '0'},
  {'name': 'WSXGA+', 'size': {'min': '1050', 'max': '1680'}, 'details': '', 'favourite': '0'},
  {'name': 'UXGA', 'size': {'min': '1200', 'max': '1600'}, 'details': '', 'favourite': '0'},
  {'name': 'WUXGA', 'size': {'min': '1200', 'max': '1920'}, 'details': '', 'favourite': '1'},
  {'name': 'QWXGA', 'size': {'min': '1152', 'max': '2048'}, 'details': '', 'favourite': '0'},
  {'name': 'QXGA', 'size': {'min': '1536', 'max': '2048'}, 'details': '', 'favourite': '0'},
  {'name': 'WQXGA', 'size': {'min': '1600', 'max': '2560'}, 'details': '', 'favourite': '0'},
  {'name': 'QSXGA', 'size': {'min': '2048', 'max': '2560'}, 'details': '', 'favourite': '0'},
  {'name': 'nHD', 'size': {'min': '360', 'max': '640'}, 'details': '', 'favourite': '0'},
  {'name': 'qHD', 'size': {'min': '540', 'max': '960'}, 'details': '', 'favourite': '0'},
  {'name': 'HD', 'size': {'min': '720', 'max': '1280'}, 'details': '', 'favourite': '0'},
  {'name': 'HD+', 'size': {'min': '900', 'max': '1600'}, 'details': '', 'favourite': '0'},
  {'name': 'FHD', 'size': {'min': '1080', 'max': '1920'}, 'details': '', 'favourite': '0'},
  {'name': 'QHD', 'size': {'min': '1440', 'max': '2560'}, 'details': '', 'favourite': '0'}
]});